version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=chageme
      - xpack.security.enabled=true
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=chageme
    ports:
      - 127.0.0.1:5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch