version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/configs/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 127.0.0.1:9090:9090
    depends_on:
      - go-tech-task

  go-tech-task:
    build: ./
    #---------------------------------------------------------------------------
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_HOST=db

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 127.0.0.1:5432:5432

  grafana:
    image: grafana/grafana:latest
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - prometheus
