version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 127.0.0.1:9090:9090
    depends_on:
      - go-tech-task

  go-tech-task:
    build: ./
    #---------------------------------------------------------------------------
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_HOST=db

  db:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node

  grafana:
    image: grafana/grafana:latest
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - prometheus
